permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Kelvin Liu
  email: liuweigg@126.com
  link: http://liuweigg.com
  weibo: http://weibo.com/u/2142212707
  github: http://github.com/liuweigg
  music: 
  linkedin: 

# 站点信息
title: 刘伟的博客
description: My personal blog
url: http://liuweigg.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: liuweigg.com

# disqus 设置
disqus:
  shortname: lw

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
