permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 许新涛
  email: x4516959621@gmail.com
  link: http://xuxintao.com
  github: http://github.com/xuxintao
  music: http://music.163.com/#/user/home?id=29737326
  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 许新涛的博客
description: My personal blog
url: http://xuxintao.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/flower.jpg
favicon: /public/img/flower.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
